### ISSUE TITLE
TensorFlow error when running gp_lstm_actuator.py

### ISSUE THREAD

**Issue by xximranxx** [alshedivat/kgp#9]
I tried to run `gp_lstm_actuator.py` as-is after running `setup.py install` and get the following error:
(Windows 7, anaconda3)

C:\Anaconda3\python.exe C:/Projects/ML/kgp/examples/gp_lstm_actuator.py
Using TensorFlow backend.
Using GPML backend with Octave engine as the default one.
Loading data...C:\Projects\ML\kgp\kgp\datasets\sysid.py:70: UserWarning: Cannot find DATA_PATH variable in the environment. Using <current_working_directory>/data/ instead.
  warnings.warn("Cannot find DATA_PATH variable in the environment. "
Done.
# of loaded points: 1024
Traceback (most recent call last):
  File "C:/Projects/ML/kgp/examples/gp_lstm_actuator.py", line 109, in <module>
    main()
  File "C:/Projects/ML/kgp/examples/gp_lstm_actuator.py", line 83, in main
    model = assemble('GP-LSTM', [nn_configs['1H'], gp_configs['GP']])
  File "C:\Projects\ML\kgp\kgp\utils\assemble.py", line 93, in assemble
    return assemble_gprnn(*params)
  File "C:\Projects\ML\kgp\kgp\utils\assemble.py", line 191, in assemble_gprnn
    RNN = assemble_rnn(nn_params, final_reshape=False)
  File "C:\Projects\ML\kgp\kgp\utils\assemble.py", line 170, in assemble_rnn
    previous = Layer(previous)
  File "C:\Anaconda3\lib\site-packages\keras-2.0.4-py3.5.egg\keras\layers\recurrent.py", line 243, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "C:\Anaconda3\lib\site-packages\keras-2.0.4-py3.5.egg\keras\engine\topology.py", line 558, in __call__
    self.build(input_shapes[0])
  File "C:\Anaconda3\lib\site-packages\keras-2.0.4-py3.5.egg\keras\layers\recurrent.py", line 1012, in build
    constraint=self.bias_constraint)
  File "C:\Anaconda3\lib\site-packages\keras-2.0.4-py3.5.egg\keras\legacy\interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\keras-2.0.4-py3.5.egg\keras\engine\topology.py", line 391, in add_weight
    weight = K.variable(initializer(shape), dtype=dtype, name=name)
  File "C:\Anaconda3\lib\site-packages\keras-2.0.4-py3.5.egg\keras\layers\recurrent.py", line 1004, in bias_initializer
    self.bias_initializer((self.units * 2,), *args, **kwargs),
  File "C:\Anaconda3\lib\site-packages\keras-2.0.4-py3.5.egg\keras\backend\tensorflow_backend.py", line 1681, in concatenate
    return tf.concat([to_dense(x) for x in tensors], axis)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1000, in concat
    dtype=dtypes.int32).get_shape(
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by alshedivat** [comment]
It looks to me like a Windows-specific issue with either Keras or Tensorflow, since the execution fails in the call to the Keras LSTM layer constructor. It perfectly works on Mac and Linux. At the moment, the package is provided "as is" for Windows users.

If you are willing to debug the issue further and discover that it is on the KGP side for some reason, I'd be happy to merge a PR that fixes it. For now, I am closing this issue.
